(() => {
  const roots=[220,196,233.08,207.65,246.94,174.61,220,185,207.65,196,233.08,174.61,220,164.81,196,233.08,207.65,185,220,196];
  const phrases=[[0,4,7,9],[0,2,7,5],[0,5,9,7],[0,4,9,7],[0,2,5,9]];
  window.LLCAmbient=class {
    constructor(){this.ctx=null;this.master=null;this.timer=null;this.next=0;this.bar=0;this.options={region:0,light:1,cap:1,musicOn:true,volume:.35};this.playing=false;this.visibility=()=>this.refresh();document.addEventListener('visibilitychange',this.visibility)}
    async start(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!this.ctx){this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=0;this.master.connect(this.ctx.destination);this.next=this.ctx.currentTime+.12;this.timer=setInterval(()=>this.tick(),350)}await this.ctx.resume();this.playing=true;this.refresh();this.tick();return true}
    update(options){Object.assign(this.options,options);this.refresh()}
    refresh(){if(!this.ctx)return;const o=this.options,enabled=this.playing&&o.musicOn!==false&&!document.hidden;const level=Math.max(0,Math.min(1,Number(o.volume)||0));this.master.gain.setTargetAtTime(enabled?level*.62:0,this.ctx.currentTime,.18)}
    note(frequency,time,duration,peak){const ctx=this.ctx;const osc=ctx.createOscillator(),harmonic=ctx.createOscillator(),tone=ctx.createGain(),edge=ctx.createGain(),filter=ctx.createBiquadFilter();osc.type='sine';osc.frequency.setValueAtTime(frequency,time);harmonic.type='triangle';harmonic.frequency.setValueAtTime(frequency*2,time);filter.type='lowpass';filter.frequency.value=1050;filter.Q.value=.35;osc.connect(tone);harmonic.connect(edge);tone.connect(filter);edge.connect(filter);filter.connect(this.master);tone.gain.setValueAtTime(.0001,time);tone.gain.exponentialRampToValueAtTime(peak,time+.035);tone.gain.exponentialRampToValueAtTime(.0001,time+duration);edge.gain.setValueAtTime(.0001,time);edge.gain.exponentialRampToValueAtTime(peak*.13,time+.045);edge.gain.exponentialRampToValueAtTime(.0001,time+Math.min(duration,1.05));osc.start(time);harmonic.start(time);osc.stop(time+duration+.04);harmonic.stop(time+duration+.04)}
    tick(){if(!this.ctx||!this.playing||document.hidden||this.options.musicOn===false)return;const ctx=this.ctx;if(this.next<ctx.currentTime-.5)this.next=ctx.currentTime+.08;while(this.next<ctx.currentTime+1){const o=this.options,region=Math.max(0,Math.min(19,Number(o.region)||0)),phrase=phrases[region%phrases.length],root=roots[region],pressure=1-Math.min(1,Math.max(0,Number(o.light||0)/Math.max(1,Number(o.cap||1)))),sequence=this.bar%2===0?[0,2,1,3]:[0,1,2],gaps=this.bar%2===0?[0,1.75,3.55,5.1]:[0,2.15,4.05],t=this.next;sequence.forEach((index,i)=>{const step=phrase[(index+this.bar)%4],frequency=root*Math.pow(2,step/12),peak=(i===0?.041:.031)*(pressure>.65?1.12:1);this.note(frequency,t+gaps[i],i===0?1.9:1.45,peak)});this.bar++;this.next+=7.8}}
    status(){return {playing:this.playing,continuousVoices:0,region:this.options.region,volume:this.options.volume}}
  };
})();
