const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = path.join(root, 'design', 'campaign-2000-preview', 'index.html');
const target = path.join(__dirname, 'index.html');
const regionMap = JSON.parse(fs.readFileSync(path.join(root, 'design', 'shadow-variants', 'region-shadow-map.json'), 'utf8'));
if(regionMap.length!==20 || regionMap.some((row,i)=>row.region!==i+1 || !(Number(row.shadow)>=1&&Number(row.shadow)<=19)))throw new Error('Invalid 20-region shadow map');
fs.writeFileSync(path.join(__dirname,'region-shadows.js'),`window.LLC_REGION_SHADOWS=${JSON.stringify(regionMap.map(row=>Number(row.shadow)-1))};\n`);
let html = fs.readFileSync(source, 'utf8');
const replaceOnce = (before, after) => {
  const count = html.split(before).length - 1;
  if (count !== 1) throw new Error(`Expected one '${before.slice(0, 65)}' marker, found ${count}`);
  html = html.replace(before, after);
};
const replaceSome=(before,after)=>{if(!html.includes(before))throw new Error(`Missing '${before.slice(0,65)}' marker`);html=html.replaceAll(before,after)};

if (!html.includes('const LEVELS=') || !html.includes('"n":2000')) throw new Error('2,000-level candidate data missing');
const levelStart=html.indexOf('const LEVELS=')+'const LEVELS='.length;
const levelEnd=html.indexOf('];',levelStart)+2;
if(levelEnd<levelStart)throw new Error('Level array end missing');
html=html.slice(0,levelEnd)+';window.LLC_CHALLENGE_REPORT=window.LLCChallenges.apply(LEVELS);window.LLC_DISABLE_ECHO=true'+html.slice(levelEnd);
replaceSome('phase2:level.phase2,active:false','phase2:level.phase2,phase3:level.phase3||0,active:false');
replaceOnce('const patrol=index===1?level.patrol:level.patrol2,phase=index===1?s.phase:s.phase2','const patrol=index===1?level.patrol:index===2?level.patrol2:level.patrol3,phase=index===1?s.phase:index===2?s.phase2:s.phase3');
replaceOnce('[[level.patrol,s.phase,1],[level.patrol2,s.phase2,2]]','[[level.patrol,s.phase,1],[level.patrol2,s.phase2,2],[level.patrol3,s.phase3,3]]');
replaceSome('if(patrol&&(eq(p,patrol[phase])','if(patrol&&(index!==3||popcount(s.mask)>=(level.patrol3Wake||1))&&(eq(p,patrol[phase])');
replaceOnce('if(level.echo&&s.trail.length){','if(level.echo&&!window.LLC_DISABLE_ECHO&&s.trail.length){');
replaceOnce('level.patrol2?.[state.phase2],level.echo?state.trail.at(-2):null','level.patrol2?.[state.phase2],level.patrol3?.[state.phase3]');
replaceOnce('for(const p of [level.patrol[state.phase],level.patrol2?.[state.phase2],level.patrol3?.[state.phase3]])','for(const p of [level.patrol[state.phase],level.patrol2?.[state.phase2],popcount(state.mask)>=(level.patrol3Wake||1)?level.patrol3?.[state.phase3]:null])');
replaceOnce('if(level.patrol2&&state.trappedPatrol!==2)state.phase2=nextShadowPhase(2)','if(level.patrol2&&state.trappedPatrol!==2)state.phase2=nextShadowPhase(2);if(level.patrol3&&state.trappedPatrol!==3)state.phase3=nextShadowPhase(3)');
replaceOnce('const patrol=state.trapPatrol===1?level.patrol:level.patrol2,phase=state.trapPatrol===1?state.phase:state.phase2','const patrol=state.trapPatrol===1?level.patrol:state.trapPatrol===2?level.patrol2:level.patrol3,phase=state.trapPatrol===1?state.phase:state.trapPatrol===2?state.phase2:state.phase3');
replaceOnce('[[1,level.patrol,state.phase],[2,level.patrol2,state.phase2]]','[[1,level.patrol,state.phase],[2,level.patrol2,state.phase2],[3,level.patrol3,state.phase3]]');
replaceSome('[level.patrol,level.patrol2].some(patrol=>','[level.patrol,level.patrol2,level.patrol3].some(patrol=>');
replaceSome('eq(p,level.patrol2?.[state.phase2])))','eq(p,level.patrol2?.[state.phase2])||eq(p,level.patrol3?.[state.phase3])))');
replaceOnce('state.trapPatrol=level.patrol.some(tile=>eq(tile,p))?1:2','state.trapPatrol=level.patrol.some(tile=>eq(tile,p))?1:level.patrol2?.some(tile=>eq(tile,p))?2:3');
replaceSome('addShadow(level.patrol2,state.phase2,travel?.shadow2From,travel?.shadow2To);','addShadow(level.patrol2,state.phase2,travel?.shadow2From,travel?.shadow2To);addShadow(level.patrol3,state.phase3);');
replaceSome('if(!state.active||!patrol)return;const pos=travel?position(from,to,eased)','if(!state.active||!patrol||patrol===level.patrol3&&popcount(state.mask)<(level.patrol3Wake||1))return;const pos=travel?position(from,to,eased)');
html=html.replaceAll('if(level.echo&&state.active&&state.trail.length>=2)','if(level.echo&&!window.LLC_DISABLE_ECHO&&state.active&&state.trail.length>=2)');
replaceOnce('+!!level.patrol2+!!level.echo+!!level.sentinelCenter','+!!level.patrol2+!!level.patrol3+!!level.sentinelCenter');
replaceOnce("if(level.echo)features.push('Echo Shadow');","if(level.echo&&!window.LLC_DISABLE_ECHO)features.push('Echo Shadow');if(level.patrolChallenge)features.push('challenge patrol');");
replaceOnce('eq(p,level.patrol2?.[state.phase2])||eq(p,level.sentinelCenter)','eq(p,level.patrol2?.[state.phase2])||eq(p,level.patrol3?.[state.phase3])||eq(p,level.sentinelCenter)');
replaceOnce('eq(p,level.patrol3?.[state.phase3])||eq(p,level.sentinelCenter)','popcount(state.mask)>=(level.patrol3Wake||1)&&eq(p,level.patrol3?.[state.phase3])||eq(p,level.sentinelCenter)');
replaceOnce('const isEcho=level.echo&&state.active','const isEcho=level.echo&&!window.LLC_DISABLE_ECHO&&state.active');
replaceOnce("if(level.echo)entries.push(['echo'","if(level.echo&&!window.LLC_DISABLE_ECHO)entries.push(['echo'");
replaceOnce('Echo still follows your trail.','All patrol shadows pause.');
replaceOnce("const night=mode==='night';", "const night=mode==='night',compact=level.grid>=12&&!canvas.parentElement.classList.contains('zoomed');");
replaceOnce("const floor=wall?(night?'#494258':'#65737f'):lit?'#8b6855'", "const floor=wall?(night?'#303c50':'#2d4353'):lit?'#286348'");
replaceOnce("wall?'#495b68':lit?'#876b55'", "wall?'#293f50':lit?'#286348'");
replaceOnce("night?((p[0]+p[1])%2?'#34374d':'#3c4155'):((p[0]+p[1])%2?'#667e88':'#77909a')", "night?((p[0]+p[1])%2?'#303d53':'#35445a'):((p[0]+p[1])%2?'#344b5a':'#3a5160')");
replaceOnce("lit?'#fbd693':wall?'#8d9aa7':night?'#6a6a83':'#a6b4b8',lit?3:1.5", "lit?'#7dffb5':compact?'#31414b66':wall?'#8d9aa7':night?'#6a6a83':'#a6b4b8',lit?4:compact?1:1.5");
replaceOnce('if(!wall&&!feature){line(x-18', 'if(!compact&&!wall&&!feature){line(x-18');
replaceOnce("41:['Echo Shadow','The echo retraces your earlier steps. Its current position is shown as a pale shadow. You cannot enter its current tile or the tile it reaches after your next tap.']","41:['Longer patrols','Watch where patrols stand now and where they will step after your next move.']");
replaceOnce('Both patrols and the Echo remain active after the first delivery.','Patrols become active after the first delivery.');
replaceOnce('s.phase,s.phase2,s.fade,s.ice,s.gate,','s.phase,s.phase2,s.phase3,s.fade,s.ice,s.gate,');
if(html.includes('for(const [patrol,phase] of [[level.patrol,s.phase],[level.patrol2,s.phase2]])if(patrol&&')){
  replaceOnce('for(const [patrol,phase] of [[level.patrol,s.phase],[level.patrol2,s.phase2]])if(patrol&&', 'for(const [patrol,phase,index] of [[level.patrol,s.phase,1],[level.patrol2,s.phase2,2],[level.patrol3,s.phase3,3]])if(patrol&&(index!==3||count(s.mask)>=(level.patrol3Wake||1))&&');
  replaceOnce('return !!(level.echo&&s.trail.some(q=>eq(q,p)))','return !!(level.echo&&!window.LLC_DISABLE_ECHO&&s.trail.some(q=>eq(q,p)))');
}else{
  const hintBlocked=/function blocked\(p,s\)\{[^\n]+\}/;
  if(!hintBlocked.test(html))throw Error('Hint shadow rule missing');
  html=html.replace(hintBlocked,'function blocked(p,s){if(!s.active)return false;for(const [patrol,phase,index] of [[level.patrol,s.phase,1],[level.patrol2,s.phase2,2],[level.patrol3,s.phase3,3]])if(patrol&&(index!==3||count(s.mask)>=(level.patrol3Wake||1))&&(eq(p,patrol[phase])||eq(p,patrol[(phase+1)%patrol.length])))return true;return false}');
}
replaceOnce('phase:item.phase,phase2:item.phase2,fade:item.fade','phase:item.phase,phase2:item.phase2,phase3:item.phase3,fade:item.fade');
replaceOnce('phase2:s.active&&level.patrol2?(s.phase2+1)%level.patrol2.length:s.phase2,','phase2:s.active&&level.patrol2?(s.phase2+1)%level.patrol2.length:s.phase2,phase3:s.active&&level.patrol3?(s.phase3+1)%level.patrol3.length:s.phase3,');
replaceOnce('<title>Last Light Courier — 2,000-map candidate campaign</title>', '<title>Last Light Courier — integrated campaign build</title>');
replaceOnce('Playable campaign preview · 200 levels', 'Integrated campaign · 2,000 levels');
replaceOnce('2,000-map review', '2,000-level map');
replaceOnce('All levels are open for this design preview.', 'All candidate levels are open for playtesting.');
replaceOnce('function rubble(x,y){ctx.save();', 'function rubble(x,y){if(window.LLCTileArt?.rubble(ctx,x,y))return;ctx.save();');
replaceOnce('function crates(x,y){ctx.save();', 'function crates(x,y){if(window.LLCTileArt?.crates(ctx,x,y))return;ctx.save();');
replaceOnce('function bridge(x,y,broken){ctx.save();', 'function bridge(x,y,broken){if(window.LLCTileArt?.bridge(ctx,x,y,broken))return;ctx.save();');
replaceOnce('function house(x,y,lit,depot=false){', 'function house(x,y,lit,depot=false){if(window.LLCTileArt?.house(ctx,x,y,lit,depot))return;');
replaceOnce('function featureArt(x,y,feature,closed){', 'function featureArt(x,y,feature,closed){if(window.LLCTileArt?.feature(ctx,x,y,feature,closed,state.gate))return;');
replaceSome('ctx.scale(.72,.72);house(0,0', 'ctx.scale(1,1);house(0,0');
replaceSome('ctx.scale(.76,.76);', 'ctx.scale(.95,.95);');
replaceOnce("const saveKey='last-light-courier-2000-candidate-v1';", "const TESTER_BUILD=false;if(TESTER_BUILD)document.body.classList.add('testerBuild');const saveKey=TESTER_BUILD?'last-light-courier-tester-v1':'last-light-courier-2000-candidate-v1';");
replaceOnce("if(!Number.isInteger(save.hints))", "save.gems=Number.isSafeInteger(save.gems)&&save.gems>=0?save.gems:0;if(!Number.isInteger(save.hints))");
replaceOnce('save.hintRewardMilestone=Math.floor(Object.keys(save.cleared).length/10)', 'save.hintRewardMilestone=Math.floor(Object.keys(save.cleared).length/5)');
replaceOnce('save.pendingHintRewards??=0;save.hintRewardMilestone??=0;', 'save.pendingHintRewards??=0;save.hintRewardMilestone??=Math.floor(Object.keys(save.cleared).length/5);');
replaceOnce('const milestone=Math.floor(Object.keys(save.cleared).length/10);if(milestone>save.hintRewardMilestone){save.pendingHintRewards+=milestone-save.hintRewardMilestone;save.hintRewardMilestone=milestone;}', 'const milestone=Math.floor(Object.keys(save.cleared).length/5);if(milestone>save.hintRewardMilestone){const earned=milestone-save.hintRewardMilestone,added=Math.min(earned,5-save.hints);save.hints+=added;save.pendingHintRewards+=earned-added;save.hintRewardMilestone=milestone;}');
replaceOnce("$('hintCount').textContent=save.hints+' / 5';$('collectHint').hidden=!(save.pendingHintRewards>0);", "if(save.pendingHintRewards>0&&save.hints<5){const added=Math.min(save.pendingHintRewards,5-save.hints);save.hints+=added;save.pendingHintRewards-=added;persist()}$('hintCount').textContent=save.hints+' / 5';$('collectHint').hidden=true;");
replaceSome('Earn one hint for every ten new levels completed.', 'A hint is added after every five new levels cleared.');
replaceOnce('  if(changed)persist();', "  if(TESTER_BUILD&&!save.testerSeeded){for(const item of POWER_CATALOG){save.powerUnlocked[item.id]=true;save.powerStock[item.id]=10}save.hints=5;save.wallet=Math.max(save.wallet,10000);save.testerSeeded=true;changed=true}if(TESTER_BUILD&&!save.testerGemsSeeded){save.gems+=200;save.testerGemsSeeded=true;changed=true}if(changed)persist();");
replaceOnce('Banked points: <strong id="mobileWallet">', 'Earned points: <strong id="mobileWallet">');
replaceOnce('function courier(x,y,moving,t){ctx.save();', 'function courier(x,y,moving,t){if(window.__appearance?.drawCourier(ctx,x,y,moving,t))return;ctx.save();');
replaceOnce('function shadow(x,y,echo=false,moving=false,t=0){ctx.save();', 'function shadow(x,y,echo=false,moving=false,t=0){if(window.__appearance?.drawShadow(ctx,x,y,echo,moving,t))return;ctx.save();');
replaceOnce("const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#2c4150');bg.addColorStop(1,'#172b3a');ctx.fillStyle=bg;ctx.fillRect(-W,-H,3*W,3*H);", "if(!window.__appearance?.drawBackdrop(ctx,W,H)){const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#2c4150');bg.addColorStop(1,'#172b3a');ctx.fillStyle=bg;ctx.fillRect(-W,-H,3*W,3*H)}");
replaceOnce("(p[0]+p[1])%2?'#4d6973':'#5a7479'", "(p[0]+p[1])%2?'#344b5a':'#3a5160'");
replaceOnce("lit?'#f9d99c':wall?'#8a9ca4':'#879ba1'", "lit?'#7dffb5':wall?'#506778':'#607c8a'");
replaceOnce("ellipse(x,y+33,39,13,'#08162488');", "ellipse(x,y+33,39,13,'#08162488');ctx.save();ctx.globalAlpha=.78;");
replaceOnce("else polygon([[x,y-th],[x+tw,y],[x,y+th],[x-tw,y]],floor,edge,2);", "else polygon([[x,y-th],[x+tw,y],[x,y+th],[x-tw,y]],floor,edge,1.2);");
replaceOnce("if(danger){ellipse(x,y,5,3,'#ff9b9e')}else if(safe){ellipse(x,y,5,3,'#c1ffe0')}", "ctx.restore();if(danger){ellipse(x,y,5,3,'#ff9b9e')}else if(safe){ellipse(x,y,5,3,'#c1ffe0')}");
replaceOnce('feedbackHistory:FEEDBACK.history};', 'feedbackHistory:FEEDBACK.history,redraw:()=>ISO.render()};');
replaceOnce('Math.max(.0002,volume)', 'Math.max(.0002,volume*(Number.isFinite(save.effectVolume)?save.effectVolume:1))');
replaceOnce('redraw:()=>ISO.render()};', 'redraw:()=>ISO.render(),setView:value=>switchView(value),setPreference:(key,value)=>{if(!["musicOn","musicVolume","soundOn","effectVolume","hapticsOn","reduceMotion","highContrast"].includes(key))return;save[key]=value;persist();FEEDBACK.labels()}};');
replaceOnce('setPreference:(key,value)=>{if(!["musicOn","musicVolume","soundOn","effectVolume","hapticsOn","reduceMotion","highContrast"].includes(key))return;save[key]=value;persist();FEEDBACK.labels()}};', 'setPreference:(key,value)=>{if(!["musicOn","musicVolume","soundOn","effectVolume","hapticsOn","reduceMotion","highContrast"].includes(key))return;save[key]=value;persist();FEEDBACK.labels()},getCurrentLevel:()=>level,buyRepairConfirmed:origin=>attemptRepair(origin,true)};');
replaceOnce('function attemptRepair(origin){', 'function attemptRepair(origin,confirmed=false,payment="gems"){if(payment!=="gems"&&payment!=="inventory")return false;');
replaceOnce('function choose(n){showScreen', `const TROPHY_CATALOG=[{id:'first-delivery',title:'First Delivery',icon:'✦',kind:'cleared',target:1,reward:100},{id:'five-roads',title:'Five Roads',icon:'◇',kind:'cleared',target:5,reward:200},{id:'ten-roads',title:'Ten Roads',icon:'✧',kind:'cleared',target:10,reward:350},{id:'twenty-five-roads',title:'Night Explorer',icon:'☾',kind:'cleared',target:25,reward:750},{id:'fifty-roads',title:'Lantern Keeper',icon:'♜',kind:'cleared',target:50,reward:1500},{id:'five-mastered',title:'Bright Routes',icon:'★',kind:'mastered',target:5,reward:250},{id:'twenty-mastered',title:'Master Courier',icon:'✶',kind:'mastered',target:20,reward:750}];
function claimTrophy(id){const award=TROPHY_CATALOG.find(item=>item.id===id);if(!award)return false;save.trophyClaims??={};if(save.trophyClaims[id])return false;const count=Object.values(save[award.kind]||{}).filter(Boolean).length;if(count<award.target||save.wallet>Number.MAX_SAFE_INTEGER-award.reward)return false;save.trophyClaims[id]=true;save.wallet+=award.reward;persist();render();return true}
function canPayRepair(payment){return payment==='inventory'?(save.powerStock?.road_repair||0)>0:payment==='gems'&&save.gems>=window.LLCGemShop.repairPrice(level.repair?.cost)}
function canRepairMove(p,payment='gems'){const r=level.repair;if(!r||r.effect!=='open'||repaired()||state.done||state.failed||state.help||state.light<=1||!canPayRepair(payment)||!eq(p,r.tile)||Math.abs(p[0]-state.pos[0])+Math.abs(p[1]-state.pos[1])!==1)return false;save.repairs[level.n]=true;const valid=legal(p);delete save.repairs[level.n];return valid}
function repairAndMove(p,payment='gems'){if(!canRepairMove(p,payment))return false;const r=level.repair;save.repairs[level.n]=true;const moved=move(p);if(!moved){delete save.repairs[level.n];return false}if(payment==='inventory'){save.powerStock.road_repair--;state.powerUsed=true}else save.gems-=window.LLCGemShop.repairPrice(r.cost);persist();render();ISO.repair(p);FEEDBACK.emit('repair');return true}
function choose(n){showScreen`);
replaceOnce('getCurrentLevel:()=>level,buyRepairConfirmed:origin=>attemptRepair(origin,true)', 'getCurrentLevel:()=>level,buyRepairConfirmed:(origin,payment="gems")=>attemptRepair(origin,true,payment),canRepairMove,repairAndMove,trophyCatalog:TROPHY_CATALOG,claimTrophy,exchangePointsForGems:(qty=1)=>{if(!Number.isSafeInteger(qty)||qty<1||qty>Math.floor(save.wallet/2000)||save.gems+qty*20>Number.MAX_SAFE_INTEGER)return false;save.wallet-=qty*2000;save.gems+=qty*20;persist();render();return true}');
replaceOnce('if(save.wallet<r.cost){const missing=r.cost-save.wallet;', 'if(payment==="inventory"&&(save.powerStock?.road_repair||0)<1)return false;if(payment==="gems"&&save.gems<window.LLCGemShop.repairPrice(r.cost)){const missing=window.LLCGemShop.repairPrice(r.cost)-save.gems;');
replaceOnce("setStatus('Not enough points','Need '+missing+' more','Bank points at the depot, then tap REPAIR again.');", "setStatus('Not enough gems','Need '+missing+' more','Exchange earned points for gems in the Shop, then try again.');");
replaceOnce('save.wallet-=r.cost;save.repairs[level.n]=true;', 'if(payment==="inventory"){save.powerStock.road_repair--;state.powerUsed=true}else save.gems-=window.LLCGemShop.repairPrice(r.cost);save.repairs[level.n]=true;');
replaceOnce('spendAnimation(rect,r.cost);', '');
replaceOnce("r.cost+' points spent. The repair is active now and remains on this level.'", "(payment==='inventory'?'One repair charge':window.LLCGemShop.repairPrice(r.cost)+' gems')+' spent. The repair is active now and remains on this level.'");
replaceOnce('const disabled=!earned||save.wallet<item.price;', 'const gemPrice=window.LLCGemShop.toolPrice(item.id),disabled=!earned||save.gems<gemPrice;');
replaceOnce("(earned?'Buy +1 · '+item.price:'Locked')", "(earned?'Buy +1 · '+window.LLCGemShop.icon+' '+gemPrice:'Locked')");
replaceOnce('Points buy optional restocks after that.', 'Gems buy optional restocks after that.');
replaceOnce("box.innerHTML='<details><summary>Earned tools and restocks</summary>", "box.innerHTML='<div class=\"powerGemBalance\">'+window.LLCGemShop.icon+' '+save.gems.toLocaleString()+' gems</div><details><summary>Earned tools and restocks</summary>");
replaceOnce('!save.powerUnlocked?.[item.id]||save.wallet<item.price', '!save.powerUnlocked?.[item.id]||save.gems<window.LLCGemShop.toolPrice(item.id)');
replaceOnce('save.wallet-=item.price;', 'save.gems-=window.LLCGemShop.toolPrice(item.id);');
replaceOnce("'One charge added to your inventory for '+item.price+' banked points.'", "'One charge added for '+window.LLCGemShop.toolPrice(item.id)+' gems.'");
replaceOnce('if(level.repair&&eq(p,level.repair.tile)&&!repaired()&&(e.target.closest(\'.repairBadge\')||!legal(p))){attemptRepair(cell);return}', "if(level.repair&&eq(p,level.repair.tile)&&!repaired()){if(level.repair.effect==='open')window.__integratedShell?.showRepairTile(cell);else attemptRepair(cell);return}");
replaceSome("if(repairTile&&repaired()&&level.repair.effect==='open')objects.push", "if(false)objects.push");
replaceOnce("if(repairTile&&(name.includes('crate')||name.includes('debris')))crates(0,0);else if(repairTile&&(name.includes('bridge')||name.includes('crossing')))bridge(0,0,true);else rubble(0,0);", "window.LLCTileArt.blocker(ctx,0,0,p,repairTile&&!repaired(),name);");
replaceOnce("repairTile&&(name.includes('crate')||name.includes('debris'))?crates(cx,cy):repairTile&&(name.includes('bridge')||name.includes('crossing'))?bridge(cx,cy,true):rubble(cx,cy)", "window.LLCTileArt.blocker(ctx,cx,cy,p,repairTile&&!repaired(),name)");
replaceOnce("if(isRepair&&!repaired())badge+='<span class=\"timer repairBadge\">REPAIR</span>';", "if(isRepair&&!repaired())badge+='<span class=\"timer repairBadge\" aria-hidden=\"true\">⚒</span>';");
replaceOnce("(isRepair&&!repaired()?', tap repair badge to buy'", "(isRepair&&!repaired()?', tap to view repair cost'");
replaceOnce('setupNavigationIcons();', fs.readFileSync(path.join(__dirname,'power-toolbar-runtime.js'),'utf8')+'\nsetupNavigationIcons();');
replaceOnce("if(lit)badge+='<span class=\"done\">✓ DONE</span>';", "if(hi>=0&&level.grid>=12)badge+='<span class=\"houseNumber '+(lit?'isLit':'')+'\">'+(lit?'✓':hi+1)+'</span>';if(lit)badge+='<span class=\"done\">✓ DONE</span>';");
replaceOnce("const classes=['cell',wall?'wall':'',feature,lit?'lit':'',", "const classes=['cell',wall?'wall':'',feature,hi>=0?(lit?'houseLit':'houseUnlit'):'',lit?'lit':'',");
replaceOnce("const p=[+cell.dataset.x,+cell.dataset.y];if(state.trapArmed", "const p=[+cell.dataset.x,+cell.dataset.y];if(!legal(p)&&!(level.repair&&eq(p,level.repair.tile)&&!repaired())&&!canTrapAt(p)&&!canDecoyAt(p)){window.__integratedShell?.inspectTile(cell);return}if(state.trapArmed");
replaceOnce("'+(!safe&&!(isRepair&&!repaired())&&!canTrapAt(p)&&!canDecoyAt(p)?'disabled':'')+'", "'+(safe?'':'tabindex=\"-1\"')+'");
replaceOnce('minimum=shortestSafeRoute(state.mask),localBest=', 'minimum=level.patrolChallenge?null:shortestSafeRoute(state.mask),localBest=');
replaceOnce("rating===null?'Route completed; no verified minimum'", "rating===null?'Route completed'");
replaceOnce("(minimum===null?'No verified minimum for this map yet; your completion is saved.':'Five stars for the shortest safe route; one star less per extra step.')", "'Your route is saved. Stars reward efficient runs.'");
replaceOnce("<strong>'+(minimum??'—')+'</strong><small>Verified minimum</small>", "<strong data-global-best>—</strong><small>All-player best</small>");
replaceOnce("(minimum===null?'':extra===0?'You matched the shortest route!':extra+' extra step'+(extra===1?'':'s')+'.')", "''");
replaceOnce('Other players’ records require an online leaderboard.', 'All-player best appears when shared results are connected.');
replaceOnce('Math.max(1.5,(level.grid||8)/6)', 'Math.max(1,(level.grid||8)/8.4)');
replaceOnce("  viewport.scrollTo({left:cell.offsetLeft+cell.offsetWidth/2-viewport.clientWidth/2,", "  const cells=[...$('board').querySelectorAll('.cell')],minLeft=Math.min(...cells.map(c=>c.offsetLeft)),maxRight=Math.max(...cells.map(c=>c.offsetLeft+c.offsetWidth)),minTop=Math.min(...cells.map(c=>c.offsetTop)),maxBottom=Math.max(...cells.map(c=>c.offsetTop+c.offsetHeight));\n  viewport.scrollTo({left:Math.max(minLeft,Math.min(Math.max(minLeft,maxRight-viewport.clientWidth),cell.offsetLeft+cell.offsetWidth/2-viewport.clientWidth/2)),");
replaceOnce("    top:cell.offsetTop+cell.offsetHeight/2-viewport.clientHeight/2,behavior:", "    top:Math.max(Math.max(0,minTop-cell.offsetHeight*.6),Math.min(Math.min(viewport.scrollHeight-viewport.clientHeight,Math.max(minTop,maxBottom-viewport.clientHeight+cell.offsetHeight*.6)),cell.offsetTop+cell.offsetHeight/2-viewport.clientHeight/2)),behavior:");
replaceOnce("const zoom=!!window.matchMedia?.('(max-width:610px)').matches&&level.grid>=16;", "const zoom=level.grid>12;");
replaceOnce("reset();$('playScreen').scrollTop=0}", "reset();if(zoom)requestAnimationFrame(focusZoomMap);$('playScreen').scrollTop=0}");
replaceOnce('Tap REPAIR on the marked tile to buy instantly with banked points.', 'Tap REPAIR on the marked tile to view the gem cost and confirm.');
replaceOnce('if(!r||repaired()||state.done||state.failed||state.help)return false;', 'if(!r||repaired()||state.done||state.failed||state.help)return false;if(!confirmed&&window.__integratedShell?.confirmRepair){window.__integratedShell.confirmRepair(origin);return false;}');
replaceOnce("hapticsOn:true,viewMode:'isometric'", "hapticsOn:true,viewMode:'overhead'");
replaceOnce("const night=mode==='night',bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,night?'#24233a':'#40596b');bg.addColorStop(1,night?'#101629':'#243d50');ctx.fillStyle=bg;ctx.fillRect(-W,-H,3*W,3*H);", "const night=mode==='night';if(night||!window.__appearance?.drawBackdrop(ctx,W,H)){const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,night?'#24233a':'#40596b');bg.addColorStop(1,night?'#101629':'#243d50');ctx.fillStyle=bg;ctx.fillRect(-W,-H,3*W,3*H)}");
if (html.split('(now-travel.start)/430').length-1!==2) throw new Error('Expected two movement animation durations');
html=html.replaceAll('(now-travel.start)/430','(now-travel.start)/(document.body.classList.contains("reduceMotion")?1:430)');
replaceOnce('if(!hasLevel)showMenu();', '/* The five-tab shell is the entry screen. */');
replaceOnce('choose(hasLevel?requested:1);', 'choose(hasLevel?requested:(LEVELS.find(l=>!save.cleared[l.n])?.n||LEVELS.length));');
replaceOnce('help:!!TUTORIALS[level.n]&&!save.seenTutorials[level.n]', 'help:false');
replaceOnce("function choose(n){showScreen('play');", "function choose(n){window.__integratedShell?.onLevelChosen(n);window.__integratedShell?.enterBoard();showScreen('play');");
replaceOnce("html+='<div class=\"boardOverlay\" role=\"alert\"><div class=\"overlayCard\"><div style=\"font-size:25px\">✦ ✦ ✦</div>", "html+='<div class=\"boardOverlay\" role=\"alert\"><div class=\"overlayCard\"><button type=\"button\" class=\"overlayClose\" data-action=\"shell-map\" aria-label=\"Close result and open map\">×</button><div style=\"font-size:25px\">✦ ✦ ✦</div>");
replaceOnce("if(what==='map')showPicker();", "if(what==='map')showPicker();if(what==='shell-map')window.__integratedShell?.navigate('map');");
replaceOnce("function showMenu(){ $('menuCleared')", "function showMenu(){if(window.__integratedShell){window.__integratedShell.navigate('map');return} $('menuCleared')");
replaceOnce('</head>', '<link rel="stylesheet" href="shell.css"><script src="gem-shop.js"></script><script src="challenge-patrols.js"></script><script src="tile-symbols.js"></script></head>');
replaceOnce('</body>', '<script src="region-shadows.js"></script><script src="ambient.js"></script><script src="player-data.js"></script><script src="shell.js"></script></body>');

const cartStart=html.indexOf('function renderPowerShop(){');
const cartComment=html.indexOf('// Let the courier choose any earned tool',cartStart);
const cartEnd=html.lastIndexOf('syncPowerUnlocks();',cartComment);
if(cartStart<0||cartEnd<0)throw new Error('Power shop insertion markers missing');
html=html.slice(0,cartStart)+fs.readFileSync(path.join(__dirname,'power-cart-runtime.js'),'utf8')+html.slice(cartComment);

html=html.trimEnd()+'\n';
fs.writeFileSync(target, html);
const testerTarget=path.join(__dirname,'tester.html');
const testerHtml=html.replace('const TESTER_BUILD=false;', 'const TESTER_BUILD=true;').replace('<title>Last Light Courier — integrated campaign build</title>','<title>Last Light Courier — tester build</title>');
if(testerHtml===html)throw new Error('Tester build flag missing');
fs.writeFileSync(testerTarget,testerHtml);
console.log(`Built player ${target} and tester ${testerTarget} from ${source}`);
