const path = require('node:path');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    executablePath: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    headless: true,
  });
  const page = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('file://' + path.resolve(__dirname,'index.html').replaceAll('\\','/'), {waitUntil:'load'});
  await page.waitForFunction(() => !!window.__campaign && !!window.__integratedShell, {timeout:30000});
  if(await page.locator('#mainMenu').isVisible())throw Error('Legacy landing page still shown on launch');
  if(await page.locator('body').getAttribute('data-screen')!=='play')throw Error('Five-tab Play screen did not open on launch');
  if(!(await page.locator('#storybookHome').isVisible()))throw Error('Storybook Play home missing on launch');
  if((await page.evaluate(()=>__campaign.getSave().viewMode))!=='overhead')throw Error('Storybook is not the initial gameplay view');
  if(await page.locator('.boardOverlay').count())throw Error('Tutorial or result overlay shown on launch');
  await page.locator('[data-home-settings]').click();
  if(!(await page.locator('#settingsPanel').isVisible()))throw Error('Settings did not open from storybook home');
  for(const key of ['musicOn','musicVolume','soundOn','effectVolume','hapticsOn','reduceMotion','highContrast'])if(await page.locator(`#integratedSettings [data-setting="${key}"]`).count()!==1)throw Error('Missing setting '+key);
  await page.locator('[data-setting="reduceMotion"]').check();
  if(!(await page.locator('body').evaluate(el=>el.classList.contains('reduceMotion'))))throw Error('Reduce motion setting did not apply');
  await page.locator('[data-setting="soundOn"]').uncheck();
  if((await page.evaluate(()=>__campaign.getSave())).soundOn!==false)throw Error('Effects toggle did not persist');
  const settingsFit=await page.locator('#settingsPanel .settingsCard').evaluate(el=>({scroll:el.scrollHeight,client:el.clientHeight}));
  if(settingsFit.scroll>settingsFit.client+2)throw Error('Settings panel requires internal scrolling at phone size: '+JSON.stringify(settingsFit));
  await page.screenshot({path:path.join(__dirname,'settings-preview.png')});
  await page.locator('#settingsClose').click();
  await page.locator('#storybookPlay').click();
  if(await page.locator('#playScreen').evaluate(el=>el.classList.contains('homeMode')))throw Error('Play did not open board');
  await page.locator('#boardLegendButton').click();
  await page.locator('[data-open-guide]').click();
  if(!(await page.locator('.boardOverlay[aria-label="How to play"]').isVisible()))throw Error('How to play is not available on demand');
  await page.locator('.boardOverlay [data-action="start"]').click();
  const data=await page.evaluate(() => ({count:__campaign.levels.length, last:__campaign.levels.at(-1).n, nav:document.querySelectorAll('#integratedNav button').length, title:document.title}));
  if(data.count!==2000 || data.last!==2000 || data.nav!==5) throw Error('Integrated data/nav mismatch: '+JSON.stringify(data));
  for(const n of [1,200,201,1000,1001,1401,2000]){
    const result=await page.evaluate(n=>{__campaign.choose(n);return {n:__campaign.getState()?.level?.n ?? __campaign.levels[n-1].n, board:document.querySelectorAll('#board .cell').length, title:document.getElementById('levelTitle').textContent}},n);
    if(!result.title.includes(String(n)) || result.board<64)throw Error('Level '+n+' failed: '+JSON.stringify(result));
  }
  await page.evaluate(()=>__campaign.choose(1));
  if(await page.locator('.boardOverlay [data-action="start"]').isVisible())await page.locator('.boardOverlay [data-action="start"]').click();
  const completion=await page.evaluate(()=>{
    const route=__campaign.levels[0].spine.slice(1);
    let accepted=0;
    for(const tile of route){if(__campaign.move(tile))accepted++;const s=__campaign.getState();if(s.done||s.failed)break;}
    const s=__campaign.getState();return {accepted,done:s.done,failed:s.failed,turns:s.turns};
  });
  if(!completion.done || completion.failed)throw Error('Level 1 normal-play route failed: '+JSON.stringify(completion));
  await page.waitForFunction(()=>window.LLCPlayerData.snapshot().recentRuns.length===1);
  const playerRecord=await page.evaluate(()=>LLCPlayerData.snapshot());
  if(!playerRecord.profile.guestId||playerRecord.bestByLevel[1]?.steps!==completion.turns)throw Error('Local player record was not stored');
  const resultText=await page.locator('.boardOverlay').textContent();
  if(resultText.includes('Verified minimum')||!resultText.includes('All-player best'))throw Error('Result still displays verified minimum or lacks all-player best');
  if((await page.locator('[data-global-best]').textContent())!=='—')throw Error('Offline result invented a global best');
  if(!(await page.locator('.boardOverlay .overlayClose').isVisible()))throw Error('Result close button missing');
  await page.screenshot({path:path.join(__dirname,'result-preview.png')});
  await page.locator('.boardOverlay .overlayClose').click();
  if(await page.locator('body').getAttribute('data-screen')!=='levels')throw Error('Result close did not open map');
  if(await page.locator('#journeyMap .journeyStop').count()!==10)throw Error('Journey map does not show ten visual stops');
  await page.locator('#journeyMap [data-stop="2"]').click();
  if(!(await page.locator('#journeyMap .journeyDetail').textContent()).includes('Level 2'))throw Error('Visual stop selection failed');
  await page.locator('#journeyMap [data-play-stop="2"]').click();
  if(!(await page.locator('#levelTitle').textContent()).includes('Level 2'))throw Error('Visual stop did not launch level');
  await page.evaluate(()=>__campaign.choose(1));
  if(await page.locator('.boardOverlay [data-action="start"]').isVisible())await page.locator('.boardOverlay [data-action="start"]').click();
  await page.locator('#integratedNav [data-destination="trophies"]').click();
  if(!(await page.locator('#integratedOverlay').isVisible()))throw Error('Trophy screen did not open');
  await page.locator('#integratedOverlay .close').click();
  await page.locator('#integratedNav [data-destination="map"]').click();
  if(await page.locator('body').getAttribute('data-screen')!=='levels')throw Error('Map navigation failed');
  await page.locator('#integratedNav [data-destination="play"]').click();
  if(await page.locator('body').getAttribute('data-screen')!=='play')throw Error('Play navigation failed');
  if(!(await page.locator('#storybookHome').isVisible()))throw Error('Play tab did not show storybook home');
  await page.locator('#storybookPlay').click();
  if(await page.locator('.gameControls').isVisible()||await page.locator('#zoomMap').isVisible())throw Error('Redundant in-level controls remain visible on a small map');
  if(!(await page.locator('.boardZoom #retry').isVisible()))throw Error('Compact restart control is missing');
  await page.locator('#integratedNav [data-destination="map"]').click();
  if(await page.locator('body').getAttribute('data-screen')!=='levels' || await page.locator('#mainMenu').isVisible())throw Error('Five-tab Map navigation failed');
  await page.locator('#integratedNav [data-destination="play"]').click();
  await page.locator('#storybookPlay').click();
  await page.waitForTimeout(350);
  const before=await page.locator('#scene').screenshot();
  await page.locator('#integratedNav [data-destination="courier"]').click();
  const pickerFit=await page.locator('.courierPanel').evaluate(el=>({scroll:el.scrollHeight,client:el.clientHeight,width:el.scrollWidth,clientWidth:el.clientWidth,couriers:el.querySelectorAll('[data-courier]').length,looks:el.querySelectorAll('[data-look]').length,shadows:el.querySelectorAll('[data-shadow]').length}));
  if(pickerFit.scroll>pickerFit.client+2||pickerFit.width>pickerFit.clientWidth+2||pickerFit.couriers!==18||pickerFit.looks!==6||pickerFit.shadows!==0)throw Error('Courier picker does not fit phone: '+JSON.stringify(pickerFit));
  await page.waitForFunction(()=>[...document.querySelectorAll('.courierPanel .appearanceGrid img')].every(img=>img.complete&&img.naturalWidth>0),{timeout:30000});
  await page.screenshot({path:path.join(__dirname,'courier-picker-preview.png')});
  await page.locator('[data-courier="3"]').click();
  await page.locator('[data-look="3"]').click();
  await page.waitForTimeout(250);
  await page.screenshot({path:path.join(__dirname,'outfit-single-preview.png')});
  await page.locator('#integratedOverlay .close').click();
  await page.waitForTimeout(350);
  const after=await page.locator('#scene').screenshot();
  if(before.equals(after))throw Error('Courier selection did not change canvas pixels');
  const selected=await page.evaluate(()=>JSON.parse(localStorage.getItem('llc-appearance-v1')));
  if(selected.courier!==3||selected.look!==3||'shadow' in selected)throw Error('Courier appearance did not persist correctly: '+JSON.stringify(selected));
  const regionShadows=await page.evaluate(()=>{__campaign.choose(10);const ember=__integratedShell.currentShadow();__campaign.choose(110);const crossroads=__integratedShell.currentShadow();return {ember,crossroads}});
  if(regionShadows.ember===regionShadows.crossroads)throw Error('Shadow did not follow region: '+JSON.stringify(regionShadows));
  const shadowActive=await page.evaluate(()=>{__campaign.choose(10);for(const tile of __campaign.levels[9].spine.slice(1,6)){__campaign.move(tile);if(__campaign.getState().active)break;}return __campaign.getState().active;});
  if(!shadowActive)throw Error('Level 10 shadow did not activate');
  await page.waitForTimeout(500);
  await page.screenshot({path:path.join(__dirname,'phone-smoke.png')});
  const desktop=await browser.newPage({viewport:{width:1468,height:1024},deviceScaleFactor:1});
  await desktop.goto('file://' + path.resolve(__dirname,'index.html').replaceAll('\\','/'),{waitUntil:'load'});
  const desktopLayout=await desktop.evaluate(()=>({shell:document.querySelector('.shell').getBoundingClientRect().width,play:document.querySelector('#playScreen').getBoundingClientRect().width,side:getComputedStyle(document.querySelector('.side')).display,menu:!document.querySelector('#mainMenu').hidden}));
  if(desktopLayout.shell>432||desktopLayout.play>430||desktopLayout.side!=='none'||desktopLayout.menu)throw Error('Desktop did not show phone layout: '+JSON.stringify(desktopLayout));
  if(await desktop.locator('.boardOverlay [data-action="start"]').isVisible())await desktop.locator('.boardOverlay [data-action="start"]').click();
  await desktop.screenshot({path:path.join(__dirname,'desktop-phone-preview.png')});
  await desktop.locator('#integratedNav [data-destination="map"]').click();
  if(await desktop.locator('#journeyMap .journeyStop').count()!==10)throw Error('Desktop journey map missing stops');
  await desktop.screenshot({path:path.join(__dirname,'journey-map-preview.png')});
  await desktop.close();
  const narrow=await browser.newPage({viewport:{width:320,height:700},deviceScaleFactor:1});
  await narrow.goto('file://' + path.resolve(__dirname,'index.html').replaceAll('\\','/'),{waitUntil:'load'});
  if(await narrow.locator('.boardOverlay [data-action="start"]').isVisible())await narrow.locator('.boardOverlay [data-action="start"]').click();
  await narrow.locator('#integratedNav [data-destination="courier"]').click();
  const narrowFit=await narrow.locator('.courierPanel').evaluate(el=>({scroll:el.scrollHeight,client:el.clientHeight,width:el.scrollWidth,clientWidth:el.clientWidth}));
  if(narrowFit.scroll>narrowFit.client+2||narrowFit.width>narrowFit.clientWidth+2)throw Error('Courier picker overflows narrow phone: '+JSON.stringify(narrowFit));
  await narrow.close();
  const repairPage=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
  await repairPage.goto('file://' + path.resolve(__dirname,'index.html').replaceAll('\\','/'),{waitUntil:'load'});
  await repairPage.waitForFunction(()=>!!window.__integratedShell);
  await repairPage.evaluate(()=>__campaign.choose(10));
  if(await repairPage.locator('.reviewPad').isVisible())throw Error('Arrow pad remains visible');
  if(!(await repairPage.locator('#repairCallout').isVisible()))throw Error('Repair card is not visible on Level 10');
  if(!(await repairPage.locator('#repairCallout').textContent()).includes('1,150'))throw Error('Level 10 repair price is missing');
  await repairPage.screenshot({path:path.join(__dirname,'repair-sample.png')});
  await repairPage.locator('#repairCallout [data-repair-open]').click();
  if(!(await repairPage.locator('.repairPanel').isVisible()))throw Error('Repair confirmation did not open');
  const walletBefore=await repairPage.evaluate(()=>__campaign.getSave().wallet);
  await repairPage.locator('[data-repair-cancel]').click();
  if((await repairPage.evaluate(()=>__campaign.getSave().wallet))!==walletBefore)throw Error('Cancelling repair spent points');
  await repairPage.evaluate(()=>{const key='last-light-courier-2000-candidate-v1',s=JSON.parse(localStorage.getItem(key));s.wallet=2000;localStorage.setItem(key,JSON.stringify(s));location.reload()});
  await repairPage.waitForFunction(()=>!!window.__integratedShell);
  await repairPage.evaluate(()=>__campaign.choose(10));
  await repairPage.locator('#repairCallout [data-repair-open]').click();
  await repairPage.screenshot({path:path.join(__dirname,'repair-confirmation-sample.png')});
  await repairPage.locator('[data-repair-approve]').click();
  const repairResult=await repairPage.evaluate(()=>({wallet:__campaign.getSave().wallet,bought:__campaign.getSave().repairs[10]}));
  if(repairResult.wallet!==850||!repairResult.bought)throw Error('Confirmed repair did not charge exact cost: '+JSON.stringify(repairResult));
  await repairPage.evaluate(()=>__campaign.choose(14));
  if(await repairPage.locator('#zoomMap').isVisible()||await repairPage.locator('.gameControls').isVisible())throw Error('Small map still shows redundant controls');
  await repairPage.waitForTimeout(1050);
  await repairPage.screenshot({path:path.join(__dirname,'streamlined-play-sample.png')});
  await repairPage.close();
  const largeMap=await browser.newPage({viewport:{width:1468,height:1024},deviceScaleFactor:1});
  await largeMap.goto('file://' + path.resolve(__dirname,'index.html').replaceAll('\\','/'),{waitUntil:'load'});
  await largeMap.waitForFunction(()=>!!window.__integratedShell);
  await largeMap.evaluate(()=>__campaign.choose(1301));
  const boardSize=await largeMap.evaluate(()=>{const v=document.querySelector('.mapViewport'),f=document.querySelector('.boardframe'),c=document.querySelector(`.cell[data-x="${__campaign.getState().pos[0]}"][data-y="${__campaign.getState().pos[1]}"]`);return {zoomed:f.classList.contains('zoomed'),rail:getComputedStyle(document.getElementById('mapIconRail')).display,viewport:v.getBoundingClientRect().width,frame:f.getBoundingClientRect().width,scrollTop:v.scrollTop,scrollHeight:v.scrollHeight,clientHeight:v.clientHeight,cellTop:c?.getBoundingClientRect().top,viewportTop:v.getBoundingClientRect().top,cellBottom:c?.getBoundingClientRect().bottom,viewportBottom:v.getBoundingClientRect().bottom}});
  if(boardSize.zoomed||boardSize.rail!=='none'||Math.abs(boardSize.frame-boardSize.viewport)>2)throw Error('Large map did not open fitted: '+JSON.stringify(boardSize));
  if(!(await largeMap.locator('#zoomMap').isVisible()))throw Error('Large map lost its fit/zoom control');
  if(boardSize.cellTop<boardSize.viewportTop||boardSize.cellBottom>boardSize.viewportBottom)throw Error('Courier is outside the initial large-map view: '+JSON.stringify(boardSize));
  const shellBox=await largeMap.locator('.shell').boundingBox();
  await largeMap.screenshot({path:path.join(__dirname,'large-map-sample.png'),clip:{x:shellBox.x,y:shellBox.y,width:shellBox.width,height:Math.min(1024-shellBox.y,shellBox.height+90)}});
  await largeMap.locator('#boardLegendButton').click();
  if(!(await largeMap.locator('.legendPanel').isVisible())||await largeMap.locator('.symbolRow').count()<3)throw Error('Map symbol help did not open');
  await largeMap.screenshot({path:path.join(__dirname,'map-symbols-sample.png')});
  await largeMap.locator('.legendPanel .close').click();
  await largeMap.close();
  const musicPage=await browser.newPage();
  await musicPage.goto('file://' + path.resolve(__dirname,'soft-music-preview.html').replaceAll('\\','/'),{waitUntil:'load'});
  await musicPage.locator('#play').click();
  await musicPage.waitForFunction(()=>music.status().playing);
  if((await musicPage.evaluate(()=>music.status().continuousVoices))!==0)throw Error('Music preview still has a continuous hum voice');
  await musicPage.locator('#region').selectOption('8');
  await musicPage.locator('#volume').fill('20');
  await musicPage.locator('#pause').click();
  if(await musicPage.evaluate(()=>music.options.musicOn)!==false)throw Error('Music preview did not pause');
  await musicPage.close();
  await page.reload({waitUntil:'load'});
  await page.waitForFunction(()=>!!window.LLCPlayerData);
  const persistedPlayer=await page.evaluate(()=>LLCPlayerData.snapshot());
  if(persistedPlayer.profile.guestId!==playerRecord.profile.guestId||persistedPlayer.bestByLevel[1]?.steps!==completion.turns)throw Error('Local player data did not survive reload');
  if(errors.length)throw Error('Browser errors: '+errors.join(' | '));
  console.log('PASS',JSON.stringify(data),'representative levels, Level 1 route, courier selection, region shadows, settings, navigation, desktop phone layout, no page errors');
  await browser.close();
})().catch(error=>{console.error(error);process.exitCode=1});
