const fs=require('fs'), path=require('path');
const dir=__dirname, src='C:\\Users\\rahul\\.codex\\generated_images\\01a1112e-3975-75e3-9146-c1ec2019c43a';
const assets=[
 ['rock-slab','exec-c56730db-b8cd-4c60-916b-5ec36e3258d3.png','permanent','Slab boulder'],
 ['rock-spires','exec-13b38a78-471f-470f-95a8-ced0d1c711df.png','permanent','Split spires'],
 ['rock-rubble','exec-7a3853db-8383-47a0-98fd-91857b125e97.png','permanent','Masonry rubble'],
 ['tree-pine','exec-716bf659-39d3-48b0-80ec-bebccbc4981d.png','permanent','Midnight pine'],
 ['tree-oak','exec-40970165-7ca6-457f-8be1-6e1bfa527cb2.png','permanent','Old oak'],
 ['tree-dead','exec-bf214e7a-8188-48c5-93d8-813670303733.png','permanent','Dead tree'],
 ['bush-thorn','exec-9471e4e6-9050-4d2d-871c-272d9721381d.png','permanent','Thorn bush'],
 ['repair-rock','exec-4e4e3ac4-c268-4204-8404-cb7f36de1a75.png','repairable','Ruptured boulder'],
 ['repair-tree','exec-b4b590fb-de46-44ac-a98b-272a614af608.png','repairable','Snapped tree'],
 ['repair-bush','exec-1f7ce656-f5b6-46b6-8731-14e2ed000841.png','repairable','Cut thorn bush'],
 ['house-unlit','exec-2414f021-94c1-476c-a72b-62ca4d1d2403.png','house','Unlit house'],
 ['house-lit','exec-f2ac57e1-a4eb-4341-9d97-ba62f188d9de.png','house','Visited house'],
 ['switch-idle','exec-9c116f71-0711-4005-a7d1-3e6f135ceee6.png','switch','Idle switch'],
 ['switch-active','exec-82b8e5d1-f200-4905-a9ed-24470c2c497e.png','switch','Active switch'],
 ['switch-expiring','exec-99a40086-f5c3-4d9b-bfe1-1b224a2bf31e.png','switch','Expiring switch']
];
for(const [id,file] of assets){const from=path.join(src,file),to=path.join(dir,id+'.png');if(!fs.existsSync(from))throw Error('Missing '+from);fs.copyFileSync(from,to)}
fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(assets.map(([id,source,type,name])=>({id,name,type,file:id+'.png',source})),null,2)+'\n');
const tile=(id,cls='')=>`<div class="tile ${cls}">${id?`<img src="${id}.png" alt="">`:''}</div>`;
const card=([id,,type,name])=>`<article class="card"><div class="big"><img src="${id}.png" alt="${name}"></div><b>${name}</b><small>${type==='permanent'?'Permanent blocker':type==='repairable'?'Damaged · repairable':'Visual concept'}</small><div class="mini">${tile(id,type==='repairable'?'repairable':'')}<span>40 px tile preview</span></div></article>`;
const repair=[['rock-slab','repair-rock','Boulder'],['tree-pine','repair-tree','Tree'],['bush-thorn','repair-bush','Bush']];
const repairCard=([blocked,broken,name])=>`<article class="repair"><h3>${name} path</h3><div class="sequence"><div>${tile(blocked)}<small>Permanent</small></div><div>${tile(broken,'repairable')}<small>Repairable</small></div><div>${tile(null,'open')}<small>Cleared road</small></div></div></article>`;
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Last Light Courier · board object concepts</title><style>
*{box-sizing:border-box}body{margin:0;background:#0d1728;color:#f4ead8;font:14px/1.4 system-ui,sans-serif}.wrap{max-width:1200px;margin:auto;padding:26px 22px 35px}h1{font:700 clamp(30px,4vw,45px) Georgia,serif;color:#f4d4a2;margin:0 0 5px}h2{font:700 28px Georgia,serif;color:#f2d6ad;margin:27px 0 9px}.sub{color:#c4ced5;max-width:900px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card,.repair,.state{background:#192c42;border:1px solid #526a7c;border-radius:12px;padding:10px}.big{height:150px;overflow:hidden;background:radial-gradient(circle at 55% 70%,#50617855,transparent 55%),#263a4e;border-radius:8px;display:grid;place-items:center}.big img{width:100%;height:100%;min-height:0;object-fit:contain}.card b{display:block;color:#ffe0ac;margin:9px 0 1px}.card small,.repair small,.state small{display:block;color:#bfcad2;font-size:11px}.mini{display:flex;gap:8px;align-items:center;margin-top:8px}.mini span{font-size:11px;color:#bfcad2}.tile{width:40px;height:40px;position:relative;display:grid;place-items:center;flex:none;background:linear-gradient(145deg,#50657a,#283a50);border:1px solid #7b8794;border-radius:4px;box-shadow:inset 0 -4px #17283b}.tile img{width:35px;height:35px;object-fit:contain;filter:drop-shadow(0 1px 1px #06101b)}.tile.repairable{background:linear-gradient(145deg,#8b7135,#584927);border:3px solid #ffdc55;box-shadow:inset 0 0 0 2px #ffe28d,0 0 6px #ffd046}.tile.repairable img{width:33px;height:33px}.tile.open{background:linear-gradient(155deg,#526f81,#324b61);border:1px solid #7692a1;box-shadow:inset 0 -4px #1b2e41}.tile.open:after{content:"";position:absolute;inset:12px 2px;border-top:2px solid #8499a0;border-bottom:2px solid #698391;transform:rotate(-25deg)}.tile.visited{border:3px solid #40e072;box-shadow:0 0 7px #32e474,inset 0 0 0 1px #c5ffd2;background:#315d50}.tile.visited:after{content:"✓";position:absolute;right:-5px;top:-7px;color:#e7fff0;background:#168e42;border:1px solid #99f5b4;border-radius:50%;font:bold 11px system-ui;width:14px;height:14px;text-align:center}.tile.switch-on{border:2px solid #fbd772;box-shadow:0 0 7px #ffcb58}.tile.switch-end{border:3px dashed #ffb44d;box-shadow:0 0 7px #f89443}.repair-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.repair h3{font:700 19px Georgia,serif;color:#ffe0aa;margin:0 0 9px}.sequence{display:flex;justify-content:space-around;gap:7px;text-align:center}.sequence>div{display:grid;justify-items:center;gap:5px}.states{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.state h3{margin:0 0 10px;color:#ffe0aa}.state .sequence{justify-content:flex-start;gap:24px}.note{color:#c3cbd1;font-size:12px;margin-top:17px}@media(max-width:760px){.grid{grid-template-columns:repeat(3,1fr)}.repair-grid{grid-template-columns:1fr}.states{grid-template-columns:1fr}}@media(max-width:480px){.wrap{padding:16px 10px}.grid{grid-template-columns:repeat(2,1fr)}.big{height:120px}.sequence{gap:4px}.state .sequence{gap:15px}}
</style><main class="wrap"><h1>Village board objects</h1><p class="sub">Original night-village storybook concepts. The large art shows shape and material; every small example uses a 40 px tile with roughly 35 px object art. Yellow marks the entire repairable tile, green marks a visited house, and the cleared road stays open.</p><h2>Permanent blockers</h2><section class="grid">${assets.filter(a=>a[2]==='permanent').map(card).join('')}</section><h2>Damaged, repairable objects</h2><section class="grid">${assets.filter(a=>a[2]==='repairable').map(card).join('')}</section><h2>Blocker → repairable → open</h2><section class="repair-grid">${repair.map(repairCard).join('')}</section><h2>House and timed switch states</h2><section class="states"><article class="state"><h3>Delivery houses</h3><div class="sequence"><div>${tile('house-unlit')}<small>Unlit</small></div><div>${tile('house-lit','visited')}<small>Visited · green</small></div></div></article><article class="state"><h3>Timed switch</h3><div class="sequence"><div>${tile('switch-idle')}<small>Idle</small></div><div>${tile('switch-active','switch-on')}<small>Active</small></div><div>${tile('switch-expiring','switch-end')}<small>Expiring</small></div></div></article></section><p class="note">Concept art and representative tiles only. Tile treatments are design proposals, not normal-play captures. No gameplay rules or playable game files were changed.</p></main></html>`;
const interactionCSS=`.interaction{margin-top:20px;padding:15px;border:1px solid #8b7a57;border-radius:13px;background:#1c3045}.interaction h2{margin:0 0 7px}.interaction p{color:#cad4db;margin:4px 0 12px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.step{border:1px solid #586d7d;border-radius:10px;padding:12px;background:#26394d;min-height:116px}.step b{display:block;color:#ffe0aa;margin-bottom:10px}.steprow{display:flex;gap:13px;align-items:center}.step small{color:#c8d1d7}.costtile{position:relative;margin-top:13px}.costbubble{position:absolute;bottom:44px;left:50%;transform:translateX(-50%);white-space:nowrap;background:#ffe29a;color:#2c251d;border:1px solid #765527;border-radius:5px;padding:2px 6px;font-weight:900;font-size:12px;box-shadow:0 2px 5px #07121d}.confirmbox{border:1px solid #d9b76e;border-radius:8px;padding:7px 10px;background:#314256;color:#fff0cf;font-size:12px}.confirmbox strong{display:block}.confirmbox em{font-style:normal;color:#bcd3d8}.demo{margin-top:14px;border-top:1px solid #617284;padding-top:13px}.demoControls{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}.demo button{cursor:pointer;border:1px solid #bca776;border-radius:7px;background:#3c4d60;color:#fff0d5;padding:7px 9px;font-weight:700}.demo button.active{background:#716044}.demoLine{display:flex;gap:16px;align-items:center;min-height:69px}.demo .target{padding:0;border:0;background:transparent}.demo .target:focus-visible{outline:2px solid #fff3b0;outline-offset:4px}.demoStatus{color:#d8e2e6}.demoPrompt{margin-top:8px;border:1px solid #d9b76e;border-radius:8px;background:#304357;padding:10px;max-width:280px}.demoPrompt[hidden]{display:none}.demoPrompt b{display:block;margin-bottom:7px}.demoPrompt button{margin-right:6px}.demo .spend{background:#8a6437}.demo .tile.open{cursor:default}@media(max-width:760px){.steps{grid-template-columns:1fr}}`;
const interactionHTML=`<section class="interaction"><h2>Repair cost and confirmation</h2><p>Example cost: 60 points. The cost label sits above the yellow tile; no small price is printed on the object.</p><div class="steps"><article class="step"><b>1 · Distant or unsafe tap</b><div class="steprow"><div class="costtile">${tile('repair-rock','repairable')}<span class="costbubble">60 points</span></div><small>Reveal price only.<br>No move or charge.</small></div></article><article class="step"><b>2 · Adjacent safe tap</b><div class="steprow"><div class="costtile">${tile('repair-rock','repairable')}<span class="costbubble">60 points</span></div><div class="confirmbox"><strong>Repair &amp; move?</strong><em>60 points · Cancel</em></div></div></article><article class="step"><b>3 · Confirmed successful move</b><div class="steprow">${tile(null,'open')}<small>Road opens; courier enters.<br>Only then deduct 60 points.</small></div></article></div><div class="demo"><strong>Try the interaction</strong><div class="demoControls"><button type="button" data-reach="distant" class="active">Nonadjacent</button><button type="button" data-reach="unsafe">Adjacent unsafe</button><button type="button" data-reach="safe">Adjacent safe</button><button type="button" id="resetDemo">Reset example</button></div><div class="demoLine"><button type="button" class="target" id="repairTarget" aria-label="Tap repairable rock"><div class="costtile">${tile('repair-rock','repairable')}<span class="costbubble" id="liveCost" hidden>60 points</span></div></button><div><strong id="wallet">120 points</strong><div class="demoStatus" id="demoStatus">Tap the yellow tile.</div></div></div><div class="demoPrompt" id="demoPrompt" hidden><b>Repair &amp; move for 60 points?</b><button type="button" class="spend" id="confirmRepair">Repair &amp; move</button><button type="button" id="cancelRepair">Cancel</button></div></div></section>`;
const interactionJS=`<script>(function(){let reach='distant',wallet=120,opened=false;const q=id=>document.getElementById(id),cost=q('liveCost'),prompt=q('demoPrompt'),target=q('repairTarget'),status=q('demoStatus');function close(){prompt.hidden=true}function reset(){wallet=120;opened=false;reach='distant';q('wallet').textContent='120 points';status.textContent='Tap the yellow tile.';cost.hidden=true;close();target.innerHTML='<div class="costtile"><div class="tile repairable"><img src="repair-rock.png" alt=""></div><span class="costbubble" id="liveCost" hidden>60 points</span></div>';for(const b of document.querySelectorAll('[data-reach]'))b.classList.toggle('active',b.dataset.reach==='distant')}for(const b of document.querySelectorAll('[data-reach]'))b.onclick=()=>{reach=b.dataset.reach;close();if(!opened)status.textContent='Tap the yellow tile.';for(const x of document.querySelectorAll('[data-reach]'))x.classList.toggle('active',x===b)};target.onclick=()=>{if(opened)return;target.querySelector('.costbubble').hidden=false;if(reach==='safe'){prompt.hidden=false;status.textContent='Safe next move: confirm or cancel.'}else{close();status.textContent=reach==='unsafe'?'Unsafe next move: cost shown, no charge.':'Not adjacent: cost shown, no charge.'}};q('cancelRepair').onclick=()=>{close();status.textContent='Cancelled: balance stays at '+wallet+' points.'};q('confirmRepair').onclick=()=>{if(reach!=='safe'||opened){close();status.textContent='Move no longer safe: no charge.';return}opened=true;wallet-=60;q('wallet').textContent=wallet+' points';target.innerHTML='<div class="tile open"></div>';close();status.textContent='Move succeeded; road open; 60 points deducted.'};q('resetDemo').onclick=reset})();</script>`;
const review=html.replace('</style>',interactionCSS+'</style>').replace('<p class="note">',interactionHTML+'<p class="note">').replace('</html>',interactionJS+'</html>');
fs.writeFileSync(path.join(dir,'index.html'),review);
console.log('Installed '+assets.length+' transparent concept PNGs and board-object review');
