(function(root){
  const base={light:42,requiredUse:true,shadows:[],help:'Deliver to every house, then return to the depot. Move one tile at a time.'};
  const levels=[
    {name:'House-triggered routes',tag:'Choose the order, open a shortcut',rule:'House 2 is reachable now by the long south road. Delivering to House 1 opens the east gate shortcut to House 2.',help:'Try House 2 first by going south from the depot, then across the bottom road. Retry and deliver House 1 first: its light opens the east gate on the upper road. Compare the routes.',map:['#########','#D...H..#','#.#.#.#U#','#.#...#.#','#.#.###.#','#......H#','#########']},
    {name:'Shadow trap',tag:'Catch a moving patrol',rule:'You have one trap in inventory. Lay it on the marked patrol tile; when the shadow steps onto it, that shadow stays frozen for the run.',help:'Approach the marked tile near the center, press Lay trap, then wait or move until the shadow enters it. Deliver only after the shadow is caught.',map:['#########','#D......#','#.#.###.#','#..Y..H.#','#.#.###.#','#.......#','#########'],shadows:[[4,3],[3,3],[4,3],[5,3]]},
    {name:'Signal bell',tag:'Redirect a patrol',rule:'Use the bell from beside it to lure the patrol away for six turns.',help:'Stand next to the bell, tap Use bell, then reach the house while the shadow is distracted.',map:['#########','#D..L...#','#.#.###.#','#.#...#H#','#.#.###.#','#.......#','#########'],shadows:[[7,2],[7,3],[7,4],[7,3]]},
    {name:'3×3 lantern ward',tag:'Make a safe pocket',rule:'Use the beacon to create a 3×3 ward for six turns. Shadows cannot catch you inside it.',help:'Activate the beacon near the center, then cross its glowing square.',map:['#########','#D......#','#.###.#.#','#....WH.#','#.###.#.#','#.......#','#########'],shadows:[[6,2],[6,3],[6,4],[7,3]]},
    {name:'Hidden houses with clues',tag:'Reveal the next delivery',rule:'Delivering to the visible house reveals the outlined house and its approach.',help:'Visit the first house at the top. The second house then appears at the lower right.',map:['#########','#D..H...#','#.#.###.#','#...#...#','#.#.###.#','#......h#','#########']},
    {name:'Repair fork',tag:'Choose one crossing',rule:'Your single free repair opens either the upper or lower bridge; the other stays closed.',help:'Stand beside either bridge and repair it. Choose a return route before you cross.',map:['#########','#D..#..H#','#...R...#','#...#...#','#...T...#','#...#...#','#########']},
    {name:'Tunnel opening',tag:'Cut a shortcut',rule:'Bore through the marked rubble tile once, creating a permanent passage for this run.',help:'Approach the rubble from the left and use the tunnel action.',map:['#########','#D..#..H#','#...#...#','#...X...#','#...#...#','#...#...#','#########']},
    {name:'Flood cycle',tag:'Cross on a dry beat',rule:'The ford is open for two turns, then flooded for two turns. Its state is always shown.',help:'Wait beside the ford until it is dry, then cross. You can wait on safe ground.',map:['#########','#D..#..H#','#...#...#','#...F...#','#...#...#','#...#...#','#########']},
    {name:'Storm gusts',tag:'Spend light against wind',rule:'Storm tiles cost three light when moving west and one light in other directions.',help:'Cross the gust lane to the house, then notice the higher light cost on the way back.',map:['#########','#D......#','#.###.#.#','#...GG.H#','#.###.#.#','#.......#','#########'],light:34},
    {name:'Earthquake',tag:'Forecast a changed street',rule:'On turn six, the marked crack opens as a crossing. The event is announced in advance.',help:'Reach the crack and wait for the turn-six quake before crossing.',map:['#########','#D..#..H#','#...#...#','#...Q...#','#...#...#','#...#...#','#########']},
    {name:'Rotating crossroads',tag:'Time your entry',rule:'The junction accepts horizontal entry on even turns and vertical entry on odd turns.',help:'Watch the junction indicator. Wait or take a side step to enter on a horizontal turn.',map:['#########','#D..#..H#','#...#...#','#...O...#','#...#...#','#...#...#','#########']},
    {name:'Nightfall phase',tag:'Lit streets matter later',rule:'From turn five, marked dark streets cost two light instead of one.',help:'Take the lower lane and cross the marked street after the nightfall clock changes.',map:['#########','#D......#','#.#####.#','#...NN.H#','#.#####.#','#.......#','#########'],light:36},
    {name:'One-use bridge',tag:'Plan another way home',rule:'The lower bridge collapses after you leave it. The upper crossing stays open for the return.',help:'Cross the lower bridge first, reach the house, then come home along the upper road.',map:['#########','#D..A..H#','#...#...#','#...B...#','#...#...#','#.......#','#########']},
    {name:'Shadow-route switch',tag:'Change the patrol circuit',rule:'Using the switch moves the patrol to a different, displayed route.',help:'Use the switch near the top before approaching the house.',map:['#########','#D..V...#','#.###.#.#','#......H#','#.###.#.#','#.......#','#########'],shadows:[[6,2],[6,3],[6,4],[7,3]],altShadows:[[2,4],[2,5],[3,5],[3,4]]},
    {name:'Alternate depots',tag:'Pick where to bank',rule:'After delivery, bank at the east depot to finish this trial. It creates a different return route.',help:'The east depot is marked E at the lower right. Reach it after the house.',map:['#########','#D......#','#.###.#.#','#...H...#','#.###.#.#','#......E#','#########'],requiredUse:false},
    {name:'Stage-earned powers',tag:'Spend one tactical charge',rule:'Choose one free power: Flare repels shadows, Anchor freezes event timing, or Sense previews patrol steps.',help:'Use one power from the action panel, then deliver and return. These are test powers, not shop items.',map:['#########','#D......#','#.###.#.#','#...F..H#','#.###.#.#','#.......#','#########'],shadows:[[6,2],[6,3],[6,4],[7,3]]}
  ].map((x,i)=>({...base,...x,id:i+1}));
  root.LAB_LEVELS=levels;
  if(typeof module!=='undefined')module.exports=levels;
})(typeof window!=='undefined'?window:globalThis);
