const Lab=require('./engine.js');
function signature(s){return [s.id,s.pos.join(','),s.turn,s.light,s.delivered.join(','),s.revealed,s.opened,s.bored,s.bridgeSpent,s.used,s.switched,s.lureUntil,s.wardUntil,s.flareUntil,s.anchorUntil,s.anchorPhase,s.senseUntil,s.power,s.trapInventory,s.trapPlaced,s.shadowTrapped,s.trappedAt?.join(',')].join('|')}
function solve(id,options={}){const start=Lab.create(id),q=[{s:start,route:[]}],seen=new Set([signature(start)]);for(let head=0;head<q.length&&head<400000;head++){const {s,route}=q[head];if(s.done)return {route,visited:head+1,light:s.light};if(s.failed||s.turn>=54)continue;for(const a of Lab.possible(s)){if(options.power&&a.type==='power'&&a.power!==options.power)continue;if(options.bridge&&a.type==='use'&&/bridge/.test(a.label)&&a.target!==options.bridge)continue;const n=Lab.advance(s,a);if(options.house2First&&n.delivered.includes(0)&&!n.delivered.includes(1))continue;if(n.failed||n===s)continue;const k=signature(n);if(seen.has(k))continue;seen.add(k);q.push({s:n,route:[...route,a.type==='move'?a.dir:a.type==='use'?a.label:a.type==='power'?a.power:'wait']})}}return {route:null,visited:q.length}}
for(let id=1;id<=16;id++){const r=solve(id);console.log(`${id}. ${Lab.levels[id-1].name}: ${r.route?`WIN ${r.route.length} turns, ${r.light} light`:'NO ROUTE'}; ${r.visited} states`);if(r.route)console.log('  '+r.route.join(' · '));else process.exitCode=1}
for(const power of ['Flare','Anchor','Sense']){const r=solve(16,{power});console.log(`Power ${power}: ${r.route?'WIN':'NO ROUTE'}; ${r.visited} states`);if(!r.route)process.exitCode=1}
const lower=solve(6,{bridge:'4,4'});console.log(`Lower repair fork: ${lower.route?'WIN':'NO ROUTE'}; ${lower.visited} states`);if(!lower.route)process.exitCode=1;
let locked=Lab.create(1);locked.pos=[7,1];if(Lab.possible(locked).some(a=>a.type==='move'&&a.dir==='down'))throw Error('east gate open before House 1');let lit=Lab.create(1);for(let x=2;x<=5;x++)lit=Lab.advance(lit,{type:'move',p:[x,1]});if(!lit.revealed||!lit.delivered.includes(0))throw Error('House 1 did not open gate');lit.pos=[7,1];if(!Lab.possible(lit).some(a=>a.type==='move'&&a.dir==='down'))throw Error('east gate stayed locked');console.log('House-triggered gate: locked before delivery, open after House 1');
const house2First=solve(1,{house2First:true});if(!house2First.route)throw Error('House 2 not reachable by south road before House 1');console.log(`House-triggered route choice: House 2 first also wins in ${house2First.route.length} turns`);
let trapped=Lab.create(2);for(const p of [[2,1],[3,1],[3,2]])trapped=Lab.advance(trapped,{type:'move',p});trapped=Lab.advance(trapped,{type:'wait'});const lay=Lab.possible(trapped).find(a=>a.type==='use'&&a.target==='3,3');if(!lay)throw Error('trap action unavailable');trapped=Lab.advance(trapped,lay);if(!trapped.shadowTrapped||trapped.trapInventory!==0)throw Error('trap did not catch shadow and consume inventory');const frozen=Lab.shadowPos(Lab.setup(2),trapped).join(',');for(let i=0;i<4;i++){trapped=Lab.advance(trapped,{type:'wait'});if(Lab.shadowPos(Lab.setup(2),trapped).join(',')!==frozen)throw Error('trapped shadow moved')}if(Lab.possible(trapped).some(a=>a.type==='use'&&a.target==='3,3'))throw Error('used trap available again');console.log('Shadow trap: one inventory charge, captured patrol remains frozen for four checked turns');
